---
- name: Download Kubernetes apt-key
  ansible.builtin.get_url:
    url:  "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: "/etc/apt/keyrings/kubernetes-apt-keyring.asc"
    mode: "0644"

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo:  "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present
    update_cache: yes
    
- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.apt:
    name:  "{{ item }}={{ k8s_version }}.*"
    state: present
    update_cache: true
  loop:
    - "kubelet"
    - "kubeadm"
    - "kubectl"

- name: Enable the Kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes
    daemon-reload: yes

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name:  "{{ item }}"
    state: present
  loop:
    - "br_netfilter"
    - "overlay"
