---
- name: Create an empty file for K8S sysctl parameters
  copy:
    content: ""
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    force: no

- name: Configure sysctl parameters for K8S
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
  with_items:
    - "net.bridge.bridge-nf-call-iptables  = 1"
    - "net.ipv4.ip_forward                 = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"

- name: Set parameters to 1 and write them into config
  sysctl:
    name:  "{{ item }}"
    value: 1
    sysctl_set: true
    reload: yes
  loop:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.ipv4.ip_forward"
    - "net.bridge.bridge-nf-call-ip6tables"